server:
  port: 8081
spring:
  redis:
    host: 192.168.74.129  #服务器地址
    port: 6379   #服务器端口号
    database: 0  #数据库索引
    jedis:
      pool:
        max-active: 50   #连接池最大连接数（使用负值表示没有限制）
        max-wait: 2000s  #连接池最大阻塞等等待时间（使用负值表示没有限制）
        max-idle: 20  #连接池最大空闲连接
        min-idle: 2   #连接池最小空闲连接
    timeout: 5000s    #连接超时时间（毫秒）